# Generated by Django 3.1 on 2020-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200822_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_card',
            name='slug',
            field=models.CharField(default='testslug', max_length=20),
        ),
    ]
