# Generated by Django 3.1 on 2020-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo_card_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_card',
            name='slug',
        ),
        migrations.AddField(
            model_name='todo_card',
            name='title',
            field=models.CharField(default='MyList', max_length=20),
        ),
    ]
