# Generated by Django 3.1 on 2020-08-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200822_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_card',
            name='items',
        ),
        migrations.AddField(
            model_name='todo_items',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.todo_card'),
        ),
    ]
