# Generated by Django 3.1 on 2020-08-23 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200823_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='Profile',
        ),
    ]
