# Generated by Django 3.1 on 2020-08-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200823_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_card',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
