# Generated by Django 3.1 on 2020-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200824_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='todo_card',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
